import { z } from 'zod';
import { siteInfoSchema } from './shared';

/**
 * Product-related Zod schemas for FlexiWoo rendering.
 *
 * These schemas validate data sent from the flexi-woo WordPress plugin.
 * WordPress/WooCommerce has several quirks that require special handling:
 * - Empty arrays [] instead of empty objects {} for some fields
 * - Numbers sent as strings (or vice versa) for attribute options
 * - Nullable fields that may be null, empty string, or missing
 */

/**
 * Product image schema.
 * WordPress generates srcset and sizes from wp_get_attachment_image_srcset().
 */
export const productImageSchema = z.object({
  id: z.number(),
  url: z.string().max(2048),
  srcset: z.string().max(4096), // Generated by wp_get_attachment_image_srcset()
  sizes: z.string().max(512), // Generated by wp_get_attachment_image_sizes()
  alt: z.string().max(512),
});

/**
 * Product attribute schema for variable products.
 *
 * WordPress quirk: The `options` array may contain term IDs (numbers) or
 * term names (strings) depending on whether it's a global or custom attribute.
 * We normalize to strings for consistent handling.
 */
export const productAttributeSchema = z.object({
  name: z.string().max(255),
  slug: z.string().max(255),
  // WordPress sends term IDs (numbers) for global attributes, names (strings) for custom
  options: z.array(z.union([z.string(), z.number()]).transform(String)).max(100),
  visible: z.boolean(),
  variation: z.boolean(), // true if this attribute is used for variations
});

const stockStatusEnum = z.enum(['instock', 'outofstock', 'onbackorder']);

export const productVariationSchema = z.object({
  id: z.number(),
  sku: z.string().max(255),
  price: z.number().min(0).max(100000000),
  price_formatted: z.string().max(50),
  regular_price: z.number().min(0).max(100000000),
  regular_price_formatted: z.string().max(50),
  sale_price: z.number().min(0).max(100000000).nullable(),
  sale_price_formatted: z.string().max(50).nullable(),
  on_sale: z.boolean(),
  stock_status: stockStatusEnum,
  stock_quantity: z.number().min(-1).max(1000000).nullable(),
  attributes: z.record(z.string().max(255), z.string().max(255)),
  image: productImageSchema.nullable(),
});

export const productCategorySchema = z.object({
  id: z.number(),
  name: z.string().max(255),
  slug: z.string().max(255),
  permalink: z.string().max(2048),
});

export const productTagSchema = z.object({
  id: z.number(),
  name: z.string().max(255),
  slug: z.string().max(255),
  permalink: z.string().max(2048),
});

export const relatedProductSchema = z.object({
  id: z.number(),
  name: z.string().max(255),
  price_formatted: z.string().max(50),
  regular_price_formatted: z.string().max(50).optional(),
  on_sale: z.boolean().optional(),
  image: productImageSchema.nullable(),
  permalink: z.string().max(2048),
});

/**
 * Grouped product child item schema.
 * Represents individual products within a grouped product.
 */
export const groupedProductSchema = z.object({
  id: z.number(),
  name: z.string().max(255),
  permalink: z.string().max(2048),
  price_formatted: z.string().max(50),
  regular_price_formatted: z.string().max(50),
  sale_price_formatted: z.string().max(50).nullable(),
  on_sale: z.boolean(),
});

export const productDimensionsSchema = z.object({
  length: z.string().max(50),
  width: z.string().max(50),
  height: z.string().max(50),
});

const productTypeEnum = z.enum(['simple', 'variable', 'grouped', 'external']);

export const productDataSchema = z.object({
  // Basic info
  id: z.number(),
  name: z.string().min(1).max(255),
  slug: z.string().max(255),
  type: productTypeEnum,
  status: z.string().max(50),
  permalink: z.string().max(2048),
  sku: z.string().max(255),

  // Pricing (max $1M = 100,000,000 cents)
  price: z.number().min(0).max(100000000),
  price_formatted: z.string().max(50),
  regular_price: z.number().min(0).max(100000000),
  regular_price_formatted: z.string().max(50),
  sale_price: z.number().min(0).max(100000000).nullable(),
  sale_price_formatted: z.string().max(50).nullable(),
  on_sale: z.boolean(),
  price_html: z.string().max(2048),

  // Description
  short_description: z.string().max(5000),
  description: z.string().max(100000),

  // Images
  image: productImageSchema.nullable(),
  gallery_images: z.array(productImageSchema).max(50),

  // Stock
  stock_status: stockStatusEnum,
  stock_quantity: z.number().min(-1).max(1000000).nullable(),
  manage_stock: z.boolean(),
  backorders_allowed: z.boolean(),
  is_low_stock: z.boolean(),

  // Variations (for variable products)
  variations: z.array(productVariationSchema).max(500),
  attributes: z.array(productAttributeSchema).max(50),
  /**
   * Default variation attributes.
   *
   * WordPress quirk: WooCommerce sends an empty array [] when no default
   * attributes are set, but sends an object { "attribute_pa_color": "red" }
   * when defaults exist. We normalize to always be an object.
   */
  default_attributes: z
    .union([z.array(z.unknown()).max(50), z.record(z.string().max(255), z.string().max(255))])
    .transform((val) => (Array.isArray(val) ? {} : val)),

  // Categories and Tags
  categories: z.array(productCategorySchema).max(100),
  tags: z.array(productTagSchema).max(100),

  // Related/Upsells
  related_products: z.array(relatedProductSchema).max(50),
  upsell_products: z.array(relatedProductSchema).max(50),

  // Grouped products (for grouped product type)
  grouped_products: z.array(groupedProductSchema).max(50).optional(),

  // External product fields (for type === 'external')
  product_url: z.string().max(2048).optional(),
  button_text: z.string().max(255).optional(),

  // Reviews
  average_rating: z.number().min(0).max(5),
  review_count: z.number().int().nonnegative().max(1000000),
  reviews_allowed: z.boolean(),

  // Additional
  weight: z.string().max(50),
  dimensions: productDimensionsSchema,
  purchasable: z.boolean(),
  virtual: z.boolean(),
  downloadable: z.boolean(),
});

/**
 * Main request schema for product rendering.
 *
 * This is the top-level schema for POST requests to /api/v1/product.
 * The flexi-woo WordPress plugin sends this data when intercepting
 * WooCommerce product pages.
 */
export const productRenderRequestSchema = z.object({
  /** WordPress site URL from get_home_url() */
  home_url: z.string().url({ message: 'Invalid URL format for home_url' }),
  /** Product data aggregated from WooCommerce */
  product_data: productDataSchema,
  /** Site configuration (currency, locale settings) */
  site_info: siteInfoSchema,
});

// Inferred types
export type ProductImage = z.infer<typeof productImageSchema>;
export type ProductAttribute = z.infer<typeof productAttributeSchema>;
export type ProductVariation = z.infer<typeof productVariationSchema>;
export type ProductCategory = z.infer<typeof productCategorySchema>;
export type ProductTag = z.infer<typeof productTagSchema>;
export type RelatedProduct = z.infer<typeof relatedProductSchema>;
export type GroupedProduct = z.infer<typeof groupedProductSchema>;
export type ProductDimensions = z.infer<typeof productDimensionsSchema>;
export type ProductData = z.infer<typeof productDataSchema>;
export type ProductRenderRequest = z.infer<typeof productRenderRequestSchema>;

// Deprecated PascalCase aliases — remove after downstream imports are updated.
/** @deprecated Use productImageSchema */
export const ProductImageSchema = productImageSchema;
/** @deprecated Use productAttributeSchema */
export const ProductAttributeSchema = productAttributeSchema;
/** @deprecated Use productVariationSchema */
export const ProductVariationSchema = productVariationSchema;
/** @deprecated Use productCategorySchema */
export const ProductCategorySchema = productCategorySchema;
/** @deprecated Use productTagSchema */
export const ProductTagSchema = productTagSchema;
/** @deprecated Use relatedProductSchema */
export const RelatedProductSchema = relatedProductSchema;
/** @deprecated Use groupedProductSchema */
export const GroupedProductSchema = groupedProductSchema;
/** @deprecated Use productDimensionsSchema */
export const ProductDimensionsSchema = productDimensionsSchema;
/** @deprecated Use productDataSchema */
export const ProductDataSchema = productDataSchema;
/** @deprecated Use productRenderRequestSchema */
export const ProductRenderRequestSchema = productRenderRequestSchema;
